### ISSUE TITLE
Sweep(slow): Basic-advance setup for the blog maker app

### ISSUE THREAD

**Issue by dropout-developer** [dropout-developer/blog-maker#3]
#### Cleanup:
- [ ] Remove any unnecessary files or boilerplate code.

#### Components:
- [ ] `BlogInputComponent`, `BlogOutputComponent`, `TableOfContentComponent`, and `SubcategoryComponent`.

#### Services:
- [ ] Setup `OpenAIService` to interact with the OpenAI API.

#### Models:
- [ ] Define `Blog` and `Subcategory` models.

#### Environment Variables:
- [ ] Add `OPEN_AI_API_KEY` to the environment variables.

#### Routes:
- [ ] Setup routes for `/create-blog` and `/blog-output`.
- [ ] Ensure the `AppComponent` has a `<router-outlet></router-outlet>` for routing.

#### File Structure:
- [ ] Organize the project files in a modular manner.
- [ ] Ensure all components, services, and models are in their respective directories.

#### Package.json:
- [ ] Update with necessary packages.
- [ ] Ensure all dependencies are correctly listed and there are no vulnerabilities.

#### Build Fixes:
- [ ] Address any build issues and ensure the app compiles without errors.
- [ ] Commit the fixes with the message "Build fixes".

#### Testing:
- [ ] Ensure the app works with a basic demo.
- [ ] Add TODOs for future improvements.
- The `AppComponent` currently lacks a `<router-outlet></router-outlet>`, which is essential for Angular routing.
- Some project files are found to be empty and need to be populated with the necessary code.
- I had to make a "build fixes" commit previously to address and resolve certain issues in the project. 

Let's ensure these concerns are addressed in the new issue for a smoother development process.
#### Note:
- Ensure the OpenAI API key can be added to the environment file and the output can be tested. Address any issues from the previous setup and ensure a smoother development experience this time around.

<details open>
<summary>Checklist</summary>

- [X] `src/app/components/blog-input/blog-input.component.ts` ✅ Commit [`bd395f3`](https://github.com/dropout-developer/blog-maker/commit/bd395f352defeb557dba16c96852cc5585870e37)
- [X] `src/app/components/blog-output/blog-output.component.ts` ✅ Commit [`8e3287c`](https://github.com/dropout-developer/blog-maker/commit/8e3287c8ce86094d972644a39ba997f0f9d31b71)
- [X] `src/app/components/table-of-content/table-of-content.component.ts` ✅ Commit [`326cdc7`](https://github.com/dropout-developer/blog-maker/commit/326cdc738fe4641846bd612ccf2e5b0aa5094275)
- [X] `src/app/components/subcategory/subcategory.component.ts` ✅ Commit [`1bec024`](https://github.com/dropout-developer/blog-maker/commit/1bec02446c455fd01be912f12cf48fdb3bf027f8)
- [X] `src/app/services/open-ai.service.ts` ✅ Commit [`86149c8`](https://github.com/dropout-developer/blog-maker/commit/86149c888134c8bf1ab92be14c9a84ce84b4832d)
- [X] `src/app/models/blog.ts` ✅ Commit [`c98ea93`](https://github.com/dropout-developer/blog-maker/commit/c98ea932ed119cbeb3e7e5c74551a241893262f9)
- [X] `src/app/models/subcategory.ts` ✅ Commit [`c45f190`](https://github.com/dropout-developer/blog-maker/commit/c45f190f390b55bfa63a71c98bbc62b19c3d1d6c)
- [X] `src/environments/environment.ts` ✅ Commit [`2d8f0fe`](https://github.com/dropout-developer/blog-maker/commit/2d8f0fea59d9c2f57c9315ceb49c6d2a35b029e2)
- [X] `src/app/app-routing.module.ts` ❌ Failed
- [X] `src/app/app.component.html` ❌ Failed
- [X] `package.json` ✅ Commit [`3c1e65b`](https://github.com/dropout-developer/blog-maker/commit/3c1e65b050a121e4e2da0a36efea1daa8320ba30)
- [X] `src/app/app.module.ts` ✅ Commit [`fe4f1a4`](https://github.com/dropout-developer/blog-maker/commit/fe4f1a47eccf438071acdf27b1e9d22cbd4bf5a3)
</details>

**Comment by kevinlu1248** [comment]
Hey @dropout-developer! I'm actually a real person. I'm responding here instead of in the PR so as to not re-trigger Sweep. 

I'm glad you're enjoying Sweep! Are you mainly using Sweep for your blog?

Also, we hardcoded the keyword "revert" to revert all changes in a file.
